module.exports = [
  // --------------------- BEGINNER (Level 1) ---------------------
  {
    name: "Bicep Curl (Dumbbell)",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Hammer Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Resistance Band Curl",
    muscleGroup: "Arms",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "15-20",
    defaultRest: "45s",
  },
  {
    name: "Bench Dip",
    muscleGroup: "Arms",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "60s",
  },
  {
    name: "Tricep Rope Pushdown",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Overhead Dumbbell Extension",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },

  // --------------------- INTERMEDIATE (Level 2) ---------------------
  {
    name: "EZ-Bar Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "10-12",
    defaultRest: "60s",
  },
  {
    name: "Barbell Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "60s",
  },
  {
    name: "Preacher Curl (Machine)",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "60s",
  },
  {
    name: "Cable Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Single-Arm Cable Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "45s",
  },
  {
    name: "Skull Crushers (EZ-Bar)",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "60s",
  },
  {
    name: "Cable Tricep Extension",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Close-Grip Push-Up",
    muscleGroup: "Arms",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-20",
    defaultRest: "60s",
  },

  // --------------------- ADVANCED (Level 3) ---------------------
  {
    name: "Weighted Dips",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Barbell Reverse Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "45s",
  },
  {
    name: "Drag Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "45s",
  },
  {
    name: "JM Press",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Overhead Cable Tricep Extension",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "45s",
  },
  {
    name: "Incline Dumbbell Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "45s",
  },
  {
    name: "Cross-Body Hammer Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "45s",
  },
  {
    name: "Reverse Grip Cable Pushdown",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },

  // --------------------- FOREARMS (Optional but Real) ---------------------
  {
    name: "Wrist Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Reverse Wrist Curl",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Farmer's Carry (Dumbbells)",
    muscleGroup: "Arms",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "30-45 sec",
    defaultRest: "60s",
  },
];
