module.exports = [
  // --------------------- BEGINNER (Level 1) ---------------------
  {
    name: "Seated Row Machine",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Lat Pulldown (Wide Grip)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "75s",
  },
  {
    name: "Lat Pulldown (Close Grip)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "75s",
  },
  {
    name: "Resistance Band Row",
    muscleGroup: "Back",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "60s",
  },
  {
    name: "Superman Raises",
    muscleGroup: "Back",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "15-20",
    defaultRest: "45s",
  },
  {
    name: "Inverted Row (Low Bar)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "75s",
  },

  // --------------------- INTERMEDIATE (Level 2) ---------------------
  {
    name: "One-Arm Dumbbell Row",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "90s",
  },
  {
    name: "Chest-Supported Row (Machine)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "75s",
  },
  {
    name: "Cable Row (Seated)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "10-12",
    defaultRest: "75s",
  },
  {
    name: "Face Pull",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "60s",
  },
  {
    name: "Straight Arm Pulldown",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Reverse Grip Lat Pulldown",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "75s",
  },

  // --------------------- ADVANCED (Level 3) ---------------------
  {
    name: "Barbell Row (Bent Over)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Deadlift",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "4-8",
    defaultRest: "120s",
  },
  {
    name: "Romanian Deadlift (Barbell)",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "120s",
  },
  {
    name: "Pull-Up",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "6-12",
    defaultRest: "90s",
  },
  {
    name: "Weighted Pull-Up",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "4-8",
    defaultRest: "120s",
  },
  {
    name: "T-Bar Row",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Pendlay Row",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "5-8",
    defaultRest: "120s",
  },
  {
    name: "Rack Pull",
    muscleGroup: "Back",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "4-8",
    defaultRest: "120s",
  },
];
