module.exports = [
  // --------------------- BEGINNER (Level 1) ---------------------
  {
    name: "Walking (Treadmill)",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-20 min",
    defaultRest: "0s",
  },
  {
    name: "Brisk Walking",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-20 min",
    defaultRest: "0s",
  },
  {
    name: "Marching in Place",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "45-60 sec",
    defaultRest: "30s",
  },
  {
    name: "Step-Up (Low Step)",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15 each leg",
    defaultRest: "45s",
  },
  {
    name: "Elliptical Trainer",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-20 min",
    defaultRest: "0s",
  },

  // --------------------- INTERMEDIATE (Level 2) ---------------------
  {
    name: "Jump Rope",
    muscleGroup: "Cardio",
    equipment: "Both",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "45-60 sec",
    defaultRest: "45s",
  },
  {
    name: "Jogging (Treadmill)",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-15 min",
    defaultRest: "0s",
  },
  {
    name: "Jogging (Outdoor)",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-20 min",
    defaultRest: "0s",
  },
  {
    name: "Cycling (Stationary)",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "15-25 min",
    defaultRest: "0s",
  },
  {
    name: "Aerobic Step Workout",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "45-60 sec",
    defaultRest: "30s",
  },
  {
    name: "Mountain Climbers",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "30-45 sec",
    defaultRest: "45s",
  },

  // --------------------- ADVANCED (Level 3) ---------------------
  {
    name: "High Knees (Fast)",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "30-45 sec",
    defaultRest: "30s",
  },
  {
    name: "Burpees",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "60s",
  },
  {
    name: "Running (Fast Pace)",
    muscleGroup: "Cardio",
    equipment: "Both",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 1,
    defaultReps: "10-15 min",
    defaultRest: "0s",
  },
  {
    name: "Sprint Intervals",
    muscleGroup: "Cardio",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 6,
    defaultReps: "20-30 sec sprint",
    defaultRest: "60-90s",
  },
  {
    name: "Rowing Machine (High Intensity)",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 1,
    defaultReps: "10 min",
    defaultRest: "0s",
  },
  {
    name: "Battle Rope Slams",
    muscleGroup: "Cardio",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "20-30 sec",
    defaultRest: "60s",
  },
];
