module.exports = [
  // --------------------- BEGINNER (Level 1) ---------------------
  {
    name: "Push-Up",
    muscleGroup: "Chest",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "60s",
  },
  {
    name: "Incline Push-Up",
    muscleGroup: "Chest",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "60s",
  },
  {
    name: "Knee Push-Up",
    muscleGroup: "Chest",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "15-20",
    defaultRest: "60s",
  },
  {
    name: "Machine Chest Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Pec Deck Machine",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },

  // --------------------- INTERMEDIATE (Level 2) ---------------------
  {
    name: "Dumbbell Bench Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "90s",
  },
  {
    name: "Incline Dumbbell Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "90s",
  },
  {
    name: "Decline Dumbbell Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "90s",
  },
  {
    name: "Chest Fly (Dumbbell)",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Cable Chest Fly",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Low to High Cable Fly",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "High to Low Cable Fly",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Bodyweight Chest Dip",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "90s",
  },

  // --------------------- ADVANCED (Level 3) ---------------------
  {
    name: "Barbell Bench Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Incline Barbell Bench Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Decline Barbell Bench Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Weighted Chest Dip",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Smith Machine Bench Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Single-Arm Cable Chest Press",
    muscleGroup: "Chest",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12",
    defaultRest: "60s",
  },
];
