module.exports = [
  // ---------------------- BEGINNER (Level 1) ----------------------
  {
    name: "Plank",
    muscleGroup: "Core",
    equipment: "Both",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "20-40 sec",
    defaultRest: "30s",
  },
  {
    name: "Knee Plank",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "20-30 sec",
    defaultRest: "30s",
  },
  {
    name: "Dead Bug",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12 each side",
    defaultRest: "45s",
  },
  {
    name: "Bird Dog",
    muscleGroup: "Core",
    equipment: "Both",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-12 each side",
    defaultRest: "45s",
  },
  {
    name: "Glute Bridge",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Standing Side Bend",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20 each side",
    defaultRest: "30s",
  },

  // ---------------------- INTERMEDIATE (Level 2) ----------------------
  {
    name: "Hanging Knee Raise",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "60s",
  },
  {
    name: "Hanging Leg Raise",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "60s",
  },
  {
    name: "Cable Crunch",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "60s",
  },
  {
    name: "Weighted Decline Sit-Up",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "60s",
  },
  {
    name: "Reverse Crunch",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "V-Ups",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "45s",
  },
  {
    name: "Russian Twists",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "20-30 total",
    defaultRest: "45s",
  },

  // ---------------------- ADVANCED (Level 3) ----------------------
  {
    name: "Hanging Toes-to-Bar",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "6-12",
    defaultRest: "75s",
  },
  {
    name: "Dragon Flag",
    muscleGroup: "Core",
    equipment: "Both",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "3-8",
    defaultRest: "90s",
  },
  {
    name: "Weighted Plank",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "40-60 sec",
    defaultRest: "60s",
  },
  {
    name: "Cable Woodchopper",
    muscleGroup: "Core",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15 each side",
    defaultRest: "60s",
  },
  {
    name: "L-Sit Hold",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-20 sec",
    defaultRest: "60s",
  },
  {
    name: "Hollow Body Hold",
    muscleGroup: "Core",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "20-40 sec",
    defaultRest: "45s",
  },
];
