module.exports = [
  // ---------------------- BEGINNER (Level 1) ----------------------
  {
    name: "Bodyweight Squat",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "45s",
  },
  {
    name: "Chair Squat",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 1,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "45s",
  },
  {
    name: "Forward Lunges",
    muscleGroup: "Legs",
    equipment: "Both",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12 each leg",
    defaultRest: "45s",
  },
  {
    name: "Glute Bridge",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Wall Sit",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "20-40 sec",
    defaultRest: "45s",
  },

  // ---------------------- INTERMEDIATE (Level 2) ----------------------
  {
    name: "Barbell Back Squat",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Leg Press",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "10-15",
    defaultRest: "75s",
  },
  {
    name: "Romanian Deadlift (Dumbbells)",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "75s",
  },
  {
    name: "Bulgarian Split Squat",
    muscleGroup: "Legs",
    equipment: "Both",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12 each leg",
    defaultRest: "60s",
  },
  {
    name: "Lateral Lunges",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-12 each side",
    defaultRest: "45s",
  },
  {
    name: "Hip Thrust",
    muscleGroup: "Legs",
    equipment: "Both",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "75s",
  },
  {
    name: "Leg Extension",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Hamstring Curl (Machine)",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Seated Calf Raise",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Standing Calf Raise",
    muscleGroup: "Legs",
    equipment: "Both",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "12-20",
    defaultRest: "45s",
  },

  // ---------------------- ADVANCED (Level 3) ----------------------
  {
    name: "Barbell Front Squat",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "5-8",
    defaultRest: "90s",
  },
  {
    name: "Barbell Romanian Deadlift",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Deficit Deadlift",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "5-8",
    defaultRest: "120s",
  },
  {
    name: "Walking Lunges (Weighted)",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15 each leg",
    defaultRest: "60s",
  },
  {
    name: "Box Jump",
    muscleGroup: "Legs",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "5-8",
    defaultRest: "60s",
  },
  {
    name: "Pistol Squat",
    muscleGroup: "Legs",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "4-8 each leg",
    defaultRest: "75s",
  },
];
