module.exports = [
  // ---------------------- BEGINNER (Level 1) ----------------------
  {
    name: "Pike Push-Up",
    muscleGroup: "Shoulders",
    equipment: "Home",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "6-12",
    defaultRest: "60s",
  },
  {
    name: "Seated Dumbbell Press (Light)",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "10-15",
    defaultRest: "75s",
  },
  {
    name: "Dumbbell Front Raise",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 2,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-15",
    defaultRest: "45s",
  },
  {
    name: "Lateral Raise",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Bent-Over Rear Delt Raise",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 1,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },

  // ---------------------- INTERMEDIATE (Level 2) ----------------------
  {
    name: "Standing Barbell Overhead Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "6-10",
    defaultRest: "90s",
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "75s",
  },
  {
    name: "Cable Lateral Raise",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Machine Shoulder Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-15",
    defaultRest: "75s",
  },
  {
    name: "Rear Delt Machine Fly",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Face Pull (Rope Cable)",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 3,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Arnold Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "8-12",
    defaultRest: "75s",
  },

  // ---------------------- ADVANCED (Level 3) ----------------------
  {
    name: "Barbell Push Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "4-6",
    defaultRest: "120s",
  },
  {
    name: "Strict Barbell Press (Heavy)",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "5-8",
    defaultRest: "120s",
  },
  {
    name: "Dumbbell Lateral Raise (Heavy/Extended Set)",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "12-25",
    defaultRest: "45s",
  },
  {
    name: "High-Incline Dumbbell Press",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 4,
    defaultReps: "8-12",
    defaultRest: "75s",
  },
  {
    name: "Rear Delt Fly (Dumbbells)",
    muscleGroup: "Shoulders",
    equipment: "Gym",
    minLevel: 2,
    maxLevel: 3,
    isCompound: false,
    defaultSets: 4,
    defaultReps: "12-20",
    defaultRest: "45s",
  },
  {
    name: "Handstand Push-Up",
    muscleGroup: "Shoulders",
    equipment: "Home",
    minLevel: 3,
    maxLevel: 3,
    isCompound: true,
    defaultSets: 3,
    defaultReps: "4-8",
    defaultRest: "90s",
  },
];
